spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./moviesdb;TRACE_LEVEL_FILE=3
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
client:
  url: "http://ec2-18-189-189-17.us-east-2.compute.amazonaws.com:8083/"