spring:
  application:
    name: sf-movies
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: @spring.profiles.active@
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

server:
  port: 8082

app:
  jwtSecret: bF0YjzmpxrgIeCvJ9ZqyxD3aIN7moi6toDA8pT6yMMetHAuxr54R2MlwE9yHPiGpzYrGd9zdAKecQIu7J1WkEg
  jwtExpirationInMs: 86400000
  basePackage: "com.csangharsha.sf_movies"
  basePath: "/api.*"