spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./moviesdb;TRACE_LEVEL_FILE=3
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
client:
  url: "http://localhost:8083"